# Generated by Django 4.0.4 on 2022-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profiles_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefixes',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
