# Generated by Django 2.1.5 on 2022-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='l_name',
        ),
        migrations.AddField(
            model_name='profiles',
            name='Firstname',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Lastname',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Prefixes',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Miss', 'Miss'), ('Ms', 'Ms')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='e_mail',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
