# Generated by Django 4.0.4 on 2022-05-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefixes',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs')], default='', max_length=60),
        ),
    ]
