# Generated by Django 4.0.4 on 2022-05-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_profiles_prefixes_alter_profiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefixes',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
