# Generated by Django 4.0.4 on 2022-06-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_profiles_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefixes', models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr')], default='', max_length=60)),
                ('Firstname', models.CharField(blank=True, default='', max_length=60)),
                ('Lastname', models.CharField(blank=True, default='', max_length=60)),
                ('e_mail', models.CharField(blank=True, default='', max_length=60)),
                ('username', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
