# Generated by Django 4.0.4 on 2022-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefixes',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
