# Generated by Django 4.0.4 on 2022-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_profile_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefixes',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mr', 'Mr')], default='', max_length=60),
        ),
    ]
