# Generated by Django 4.0.5 on 2022-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('Duration', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
